API Resources (To develop)
storyn26383/nuxt-starter pull request #5
Opened 2020-01-16 03:25 UTC by sather33

## 實作

### getResource()
- 用來取得設定檔 `xx.json`。
- 選 `json` 是因為格式是 `Object`，可以直接把資料拿來用。

### class Parser
- 會做成 class 是為了讓 `configs` 不用一直作為 `argument` 傳入 `parse()`。

2020-01-16 03:33 UTC, storyn26383 requested changes
記得過 code lint 😇

2020-01-16 03:33 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    '@/plugins/api-resources'
上面要加 `,`，而且是每個 else if 裡都要 XD

2020-01-16 03:33 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    '@/plugins/api-resources'
BTW，第一行不能用 require，幫我改成 import，我之前沒注意到 sorry

2020-01-16 06:14 UTC, sather33 commented on template/nuxt/plugins/api-resources.js
> +    return require(`~/config/api/${model}/${method}`)
這個靜態的設定檔，是不是放在 `/static` 會比較妥當？
https://zh.nuxtjs.org/guide/assets#%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6

2020-01-16 07:36 UTC, storyn26383 requested changes

2020-01-16 07:36 UTC, storyn26383 commented on template/nuxt/plugins/api-resources.js
> +}
1. 為什麼會想用分開的檔案分開載入，而不是一大包檔案一次載入呢？
2. 你違反了 SOLID 裡的 L 原則

2020-01-16 07:36 UTC, storyn26383 commented on template/nuxt/plugins/api-resources.js
> +    const isParseToQuery = type === 'query'
第一行就告訴我們這個 method 違反了 SOLID 的 S，所以你下面才有奇妙判斷

2020-01-16 07:36 UTC, storyn26383 commented on template/nuxt/plugins/api-resources.js
> +const transResource = (resource, configs) => {
1. trans 是什麼的縮寫呢？我們要避免只有自己看得懂的縮寫
2. resource 跟 config 好像是一樣的東西？只是來源不同
3. 這個 function 看起來是在做 merge 的動做？

2020-01-16 07:36 UTC, storyn26383 commented on template/nuxt/plugins/api-resources.js
> +    return $axios(path, { data: params, method, headers })
1. 可以只用一個參數
2. 改用 `$axios.$request`

2020-01-16 07:37 UTC, storyn26383 commented on template/nuxt/plugins/api-resources.js
> +    return require(`~/config/api/${model}/${method}`)
不是 XD

2020-01-16 07:50 UTC, sather33 commented on template/nuxt/plugins/api-resources.js
> +    const isParseToQuery = type === 'query'
我本來是拆開，但因為兩種解析方式很像，所以合併。

2020-01-16 08:33 UTC, sather33 commented on template/nuxt/plugins/api-resources.js
> +}
### 結論：
採用『一次性載入』
### 理由：
之前想分開是為了 **『好管理、容易找到檔案並且看裡面的內容』** 。
但是這個檔案不應該是要來 **『閱讀』** 的，要閱讀應該要看 API 文件。
而且如果只有個檔案，也好修改，直接整個覆寫就好。

2020-01-16 08:37 UTC, sather33 commented on template/nuxt/plugins/api-resources.js
> +const transResource = (resource, configs) => {
已大改。

我把設定檔取名 `api-configs.json`，並且放在 `api.js` 旁邊。

2020-01-16 08:41 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +import apiConfigs from './api-configs'
設定檔叫 `api-configs.json` 且放在這 `api.js` 旁邊。
未來還會有 `axios-mock-adapter.js`，都會一起放在這 `/plugins/api-resources` 資料夾裡面。

2020-01-16 08:41 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +    const apiConfig = apiConfigs[action]
改成 `apiConfigs` 之後就可以很簡單的用 `action` 來知道有沒有設定檔。

2020-01-16 08:41 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +    const { method, path, headers, params } = mergeConfig(apiConfig, configs)
改成 `mergeConfig`，因為他在合併『設定檔』跟『api 所需的資料』。

2020-01-16 08:43 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +      throw new Error(error)
這邊使用一層 `try catch` 是為了接下 api 失敗的 `error` 。
並且用 `throw new Error` 取代 `Promise.reject()`，因為 `$axios` 成功的話是拿到 `Object`。

2020-01-16 09:39 UTC, sather33 commented
新增 `parsePath`

2020-01-16 10:43 UTC, storyn26383 requested changes

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +import apiConfigs from './api-configs'
我個人偏好放在 `~/definitions/api.js`

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    return path.replace(/{(\w+?)}/g, (keyWithBlock) => {
試試下面這個
```js
(match, key) => { /* ... */ }
```

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +class Parser {
你裡面全都不是在做 parser 該做的事情耶...
我覺得用兩個 function 就好了
`buildPath` `buildData`

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  const api = async (action, configs) => {
叫 action 跟 data 好了

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    const apiConfig = apiConfigs[action]
我覺得他應該要叫做定義檔，而不是設定檔

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +      throw new Error(error)
你不用這麼麻煩，直接 `return $axios.$requeset` 就好

2020-01-16 10:43 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +const mergeConfig = (apiConfig, configs) => {
叫 buildAxiosConfig 吧～
然後回傳的東西直接是 axios config 的格式

2020-01-17 02:56 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +  const api = async (action, configs) => {
可以維持 `action` 跟 `configs` 嗎？ 如果叫 data 的話會跟 `buildAxiosConfig` 和 `definition` 裡的 data 衝突。

2020-01-17 03:19 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  const api = async (action, configs) => {
主要是因為你帶的東西，不是 params 就是 query，叫 config 好像有點怪，不然我再想想還有什麼合適的好了 QQ

2020-01-17 03:21 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +  const api = async (action, configs) => {
好，我再想想看

2020-01-17 03:23 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  const api = async (action, configs) => {
requestItems 好了 XD

2020-01-17 04:09 UTC, sather33 commented
@storyn26383  我把程式碼重構了，很怕矯枉過正哈哈，本來還想切細一點。
昨天有討論到用 3 個參數 `(action, requestItems, headers)`，但我還是想保持現在的做法 2 個參數就好。如果『真的』要用 headers ，只需要同樣放在 `requestItems` 裡就好，在 `build()`的時候會自動去依照 api 的設定檔加入 headers。

2020-01-17 04:28 UTC, storyn26383 requested changes

2020-01-17 04:28 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    }, {})
```js
const result = {}

for (key in definitions) {
  const { required, default: defaultValue } = definitions[key]
  const value = this.requestItems[key] || defaultValue

  if (value !== null) {
    result[key] = value

    continue
  }

  if (required) {
    throw new Error('...')
  }
}

return result
```

2020-01-17 04:28 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    }, {})
雖然程式變長了，但也變好懂了

2020-01-17 04:28 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  isSetValueToData (key, data) {
這個我看了好久才看懂是什麼意思...

2020-01-17 04:28 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  getRequestValue (key) {
其實沒有很需要他

2020-01-17 04:28 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  buildData (data) {
我覺得改成 `buildRequestItems (definitions)` 好像會好一點

2020-01-17 04:28 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +  constructor (definition, requestItems) {
`definitions` 用複數

2020-01-17 05:49 UTC, storyn26383 approved these changes
恭喜你終於完成了～～～

2020-01-17 05:52 UTC, sather33 commented
> 恭喜你終於完成了～～～

感動😭

2020-01-17 05:52 UTC, merged