Features/axios mock adapter
storyn26383/nuxt-starter pull request #6
Opened 2020-01-17 07:31 UTC by sather33

## Axios mock adapter 實作
### `~/definitions/env.js`
- 加入 `env.js` 檔案。

### `~/plugins/api-resources/axios-mock-adapter.js`
- 新增一個 `class ActionAdapter` 專門 `mock(action)`。

2020-01-17 07:44 UTC, sather33 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +    return path.replace(/{(\w+?)}/g, '1')
我這邊很單純的把所有在 url 的變數全部變成 `1`。因為不需要知道 id 是多少。

2020-01-17 07:44 UTC, sather33 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +    this.mockAdapter = mockAdapter
把 `mockAdapter` 注入進來，因為這個 `mockAdapter` 不能宣告很多個，舉例。
```ts
const mockAdapter = new MockAdapter($axios)
const mockAdapter2 = new MockAdapter($axios)
...
mockAdapter.mock(...)
mockAdapter2.mock(...) // 這樣會只有 mockAdapter2 被 mock，上面那個 mockAdapter 會被覆蓋。
```

所以把 `mockAdapter` 從外面拿進來用。

2020-01-20 03:08 UTC, storyn26383 requested changes

2020-01-20 03:08 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +import env from './definitions/env.js'
參考[這個 commit](https://github.com/Fontech/next-drive/commit/84c45c30cc81813e0355a328c8c1e6c2cea1f6c4)，用 dotenv 來做

2020-01-20 03:08 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +    return path.replace(/{(\w+?)}/g, '1')
那為何不如就不 replace 了 XD

2020-01-20 03:08 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +    const onWhichMethod = `on${method[0].toUpperCase() + method.slice(1).toLowerCase()}`
https://github.com/UniSharp/helpers.js/blob/master/src/string/index.js#L28

2020-01-20 03:08 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +  if (app.context.env.useMockApi) {
return first

2020-01-20 03:08 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +class ActionAdapter {
這東西不叫 adapter 唷，比較像是 decorator

2020-01-21 02:29 UTC, sather33 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +  if (app.context.env.useMockApi) {
這邊可以 return null 嗎？

2020-01-21 03:06 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +  if (app.context.env.useMockApi) {
可以，因為你有講到重點，他是不回傳東西的，所以直接像下面這樣就好

```js
if (!app.context.env.useMockApi) {
  return
}
```

2020-01-21 03:50 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: process.argv.includes('--use-mock-api')
這樣就可以使用 `yarn dev --use-mock-api`

2020-01-21 03:50 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +    return path
因為在 `axios-mock-api` 要 mock 的 `path` 會是 `/player/{id}`，所以如果 `axiosConfig.build()` 產生的 `path` 不是 `/player/{id}` 的話，會無法 mock 成功。

2020-01-21 04:09 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: process.argv.includes('--use-mock-api')
這兩個你要擇一，不可以又 ENV 又 ARGV

2020-01-21 05:59 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: process.argv.includes('--use-mock-api')
新增 script `dev:use-mock-api: "USE_MOCK_API=1 nuxt"`

2020-01-21 06:00 UTC, storyn26383 requested changes

2020-01-21 06:00 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
這行不需要才對

2020-01-21 06:00 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    }
這裡可以用工廠模式來做

2020-01-21 06:00 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    return path
那這個 path 是打算做什麼 @@？
沒有很懂 XD

2020-01-21 06:01 UTC, storyn26383 commented
記得補上 .env.example

2020-01-21 06:04 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +    return path
因為本來的 buildPath() 會把 path `/player/{id}` 變成 `/player/2` 或其他 id。
但是在 axios-mock-api 中是這樣。
```
mock.onPost('/player/{id}', ...)。
```
所以 `$axios` 對 `/player/2` 發出 request 的時候會 axios-mock-adapter 會 mock 不到。
因為 path 不一樣。

2020-01-21 06:04 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
他不會自動用進去 env

2020-01-21 06:05 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
如果要自動的話就要用 `NEXT_ENV_USE_MOCK_API`，要改這樣？

2020-01-21 06:06 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
https://github.com/nuxt-community/dotenv-module#usage

2020-01-21 06:06 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
我記得會，他也寫會耶 @@

2020-01-21 06:07 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
> 如果要自動的話就要用 NEXT_ENV_USE_MOCK_API，要改這樣？
看不懂 @@

2020-01-21 06:09 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
https://nuxtjs.org/api/configuration-env/#automatic-injection-of-environment-variables

2020-01-21 06:09 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    return path
哦～聽懂，那看起來要像下面這樣做

2020-01-21 06:09 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
> 我記得會，他也寫會耶 @@

寫在 `.env` 檔案裡可以，但是指令裡的不行

2020-01-21 06:10 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    return path
```js
mock.onGet(/\/users\/\d+/).reply(/* ... */);
```

2020-01-21 06:11 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
你是說 `USE_MOCK_API=1 yarn dev` 這種的，在程式裡面用 `process.env.USE_MOCK_API` 會抓不到嗎？

2020-01-21 06:19 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
> 你是說 `USE_MOCK_API=1 yarn dev` 這種的，在程式裡面用 `process.env.USE_MOCK_API` 會抓不到嗎？

process.env.USE_MOCK_API 在 server，但 `context.env.USE_MOCK_API` 沒有。
 `axios-mock-api` 跟 `api-resources` 需要從 `context.env` 來拿資料。

2020-01-21 06:23 UTC, storyn26383 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
我猜應該是有 BUG，之後看看會不會修好，先照你這樣用吧～

2020-01-21 06:26 UTC, sather33 commented on template/nuxt/nuxt.config.js
> +    USE_MOCK_API: !!process.env.USE_MOCK_API
`dotenv` 好像沒有把指令的變數『自動帶入』context.env。
剛好在 `nuxt.config.js` 裡可以用 `process.env. USE_MOCK_API` 抓到變數，所以我就把他放入 `env` 裡，這樣 `context.env` 也有資料了。

2020-01-21 07:28 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +    const axiosConfig = configMaker.createAxiosConfig(type)
@storyn26383  是這樣嗎？

2020-01-21 08:04 UTC, storyn26383 requested changes

2020-01-21 08:04 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +    const axiosConfig = configMaker.createAxiosConfig(type)
這樣就耦合啦，我們用工廠的目地是要把這個判斷藏起來，你這樣不就跑出來了 XD

```js
createAxiosConfig () {
  if (process.env.USE_MOCK_API) {
    return new MockedAxiosConfig(this.definitions, this.requestItems)
  }

  return new AxiosConfig(this.definitions, this.requestItems)
}
```

2020-01-21 08:04 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/api.js
> +class ConfigMaker {
用 AxiosConfgMaker 或是 AxiosConfigFactor 都行，但就是不可以只有 Config
不過如果是我，不會特別拉一個 class 出來，我會寫一個 createAxiosConfig 的 function

2020-01-21 08:04 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +    this.definitions = definitions
這個不應該被注入

2020-01-21 08:04 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +  mock (action) {
你應該是要直接帶 definition 進來，而不是帶 action 進來再去 definitions 裡去找東西出來，因為這樣就跟 definitions 有高度耦合

2020-01-21 08:04 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +import MockAdapter from 'axios-mock-adapter'
我認為直接叫 `AxiosMockAdapter` 是比較好的

2020-01-21 08:04 UTC, storyn26383 commented on template/nuxt/plugins/api-resources/axios-mock-adapter.js
> +class ActionDecorator {
我想了超級無敵久，我覺得最適合他的名字，應該是 AxioMockAdapterProxy
那為什麼不用 decorator 而用 proxy 呢？可以參考 decorator、proxy 模式，應該就會知道原因

2020-01-21 08:51 UTC, sather33 commented on template/nuxt/plugins/api-resources/api.js
> +    return $axios.$request({ ...axiosConfig.build(definitions, requestItems) })
把 `definitions` 跟 `requestItems `  移到 `build()` 這，程式碼清楚多了。

2020-01-21 16:26 UTC, storyn26383 approved these changes
超讚的，不錯不錯～

2020-01-22 02:14 UTC, merged